### ISSUE TITLE
Obmcutil getsensors can not work

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#112]
As title. Please see the below figure.
![sensorerror](https://cloud.githubusercontent.com/assets/15260220/16330394/6fec7cbc-3a1b-11e6-91e7-f1e1a9331646.jpg)

**Comment by bradbishop** [comment]
At some point a floating point was added to a sensor.  obmcutil doesn't handle floats...this broke then.  I have a fix...will open PR today.

**Comment by bradbishop** [comment]
Found the commit that broke: 
https://github.com/openbmc/skeleton/commit/a8260c83d6566fc46832c627ae32c996cfb76ea4
