### ISSUE TITLE
Set Value by dbus is not work.

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#113]
We use the below function to change fan speed in fan algorithm,

rc = sd_bus_call_method(bus, // On the System Bus
gService, // Service to contact
fanObjPath[i], // Object path
gIntPath, // Interface name
"setValue", // Method to be called
&bus_error, // object to return error
&response, // Response message on success
"i", // input message (string,byte)
FinalFanSpeed); 

But after I merged the latest code in Skeleton, I found the value can not be set.

After debug, it seems like the below commit make it fail.

https://github.com/openbmc/skeleton/commit/efc689707d21f36c0ed8f0b1af474d2087ef8f95

I tried to modified hwmon.py to oringinal from the commit, then setValue worked.

**Comment by bradbishop** [comment]
Hi Ken

You are correct, that is the offending commit.  Reverted...

**Comment by Kenthliu** [comment]
It's fixed in 1.01. Thanks.
