### ISSUE TITLE
BIOS version doesn't show via openBMC REST

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#116]
With newer BMC releases (v1.0) and BIOS releases (V 0.2.2) I am noticing that we can't get the BIOS version info with curl command via the BMC (even when host is up).  But BMC v0.8 was work.
BMC 0.8 and BIOS 0.2.2
![0 8 0 2 2](https://cloud.githubusercontent.com/assets/15260220/16442425/06686af6-3e05-11e6-82e4-e866eae77f3f.jpg)
BMC 1.0 and BIOS 0.2.2
![1 0 0 2 2](https://cloud.githubusercontent.com/assets/15260220/16442438/1f7100da-3e05-11e6-8d65-0422a6ec3754.jpg)

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc #423](https://github.com/openbmc/openbmc/issues/423) via [**ZenHub**](https://www.zenhub.com/)
