### ISSUE TITLE
[skeleton/openbmc-v1.0-stable] Fail sync MAC from io_board fru if using random MAC address by default

### ISSUE THREAD

**Issue by johnhcwang** [openbmc/skeleton#129]
If we didn't set 'ethaddr' in uboot, random locally administered address would be used by default.
In this case, MAC can't be sync even if we had configured the address in io_board FRU Custom Filed 2 since [here](https://github.com/openbmc/skeleton/blob/openbmc-v1.0-stable/pyinventorymgr/sync_inventory_items.py#L73).

**Comment by gwshan** [comment]
The description from @johnhcwang is accurate and complete. I'm putting a note here for the correct procedure to update the MAC address manually:
- Bring down the interface      ("ifconfig eth0 down")
- Set the new MAC address   ("ifconfig eth0 hw ether xx:xx:xx:xx:xx:xx")
- Bring up the interface          ("ifconfig eth0 up")

**Comment by williamspatrick** [comment]
@gwshan - Please be careful about recommending commands like this.  We use systemd's networkd for controlling the network interfaces, so by doing these ifconfig commands you are bypassing that.

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc #627](https://github.com/openbmc/openbmc/issues/627) via [**ZenHub**](https://www.zenhub.com/)
