### ISSUE TITLE
Updating BIOS via REST API wipes out the Boot options (NVRam)

### ISSUE THREAD

**Issue by agangidi53** [openbmc/skeleton#132]
The current update BIOS via BMC TFTP REST API feature does not persist boot options (stored in NVRAM partition of BIOS). It would nice to provide a flag to persist or clear the host boot options before doing the update.

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc #709](https://github.com/openbmc/openbmc/issues/709) via [**ZenHub**](https://www.zenhub.com/)
