### ISSUE TITLE
Convert obmcutil from python to bash

### ISSUE THREAD

**Issue by anoo1** [openbmc/skeleton#136]
Python takes up flash space, so there has been discussions on making python option in openbmc. Therefore obmcutil would need to be made a bash script so that it run on systems that have images with no python installed.

**Comment by bjwyman** [comment]
Start: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/12798
Done? -> https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-state-manager/+/14590

**Comment by anoo1** [comment]
Yeah this is done, thanks. Closing.

**Comment by amboar** [comment]
It is missing `-v` / `--verbose` though :/

**Comment by bjwyman** [comment]
Lack of verbose was noted in a commit message: https://github.com/openbmc/phosphor-state-manager/commit/3ae0a3549adbd98ea0dbeedb2caa76ed8283472c

**Comment by amboar** [comment]
Right, but that doesn't really help the people who were expecting it to be there?

**Comment by bjwyman** [comment]
Create a story to add the verbose option?

**Comment by amboar** [comment]
Sure, or I could just send a patch. But the point was that we arbitrarily broke a user interface, and that's not really okay as it breaks people's workflows. We need to avoid that, it creates a lot of frustration with users.
