### ISSUE TITLE
palmetto chassis_powerControl

### ISSUE THREAD

**Issue by wws66** [openbmc/skeleton#137]
Hello everyone, I sent the on / off command through obmcutil. For the shutdown command, its execution result is normal, but there are some problems in the startup command. When we execute the startup command, we delay the start of the server for 31s, but at this time, we find that the current server status is changed incorrectly. It shows that the current server is in the off state, but it is in the off state After a delay of 31s, the machine is started successfully. When we send the shutdown command again, we need to execute the startup command again and execute the shutdown command within the delay of 31s because of the error of the identified state. Can you help us？

**Comment by mdmillerii** [comment]
> It shows that the current server is in the off state, but it is in the off state After a delay 

Can you proofread?  The desired and actual state are off in the above statement.

The power control for Palmetto, like all supported OpenPOWER systems, use a `desired state` GPIO, where the state of a GPIO tells the power subsystem the desired system power state.   The GPIO does not represent a momentary button press.

Also, if you are talking about the power off, there is the concept of soft and hard power off.  The soft off send a notificaton to the host and waits for a timeout or for the host to respond with an inband power off request which is considered to be a hard off.

Please consider asking questions on IRC or via email.
https://github.com/openbmc/docs/#contact
