### ISSUE TITLE
maintainer needed

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/skeleton#138]
@spinler to ask around at IBM if there is someone who would like to be a maintainer of this.  There should be very limited use of this repository still but I think there is some code used in the Witherspoon power-on sequence still.

**Comment by spinler** [comment]
@anoo1 volunteered, and will put up a commit.

**Comment by anoo1** [comment]
> @anoo1 volunteered, and will put up a commit.

https://gerrit.openbmc.org/c/openbmc/skeleton/+/57898
