### ISSUE TITLE
Sensor 5 not showing bus 

### ISSUE THREAD

**Issue by causten** [openbmc/skeleton#14]
I put on commit 87493b814e72281faf00fa909868714aee8f76d4
I now can get a bus interface for 9 but not for 5.

=== No Worky ===
 curl -d "[ \"SENSOR\", 5 ]" http://9.3.164.147/org/openbmc/managers/System/action/getObjectFromByteId{
  "result": [
    "", 
    "/org/openbmc/sensor/virtual/BootProgress", 
    "org.openbmc.InventoryItem"
  ], 
  "status": "OK"
}

=== Works ===
curl -d "[ \"SENSOR\", 9 ]" http://9.3.164.147/org/openbmc/managers/System/action/getObjectFromByteId
{
  "result": [
    ":1.18", 
    "/org/openbmc/sensor/virtual/BootCount", 
    "org.openbmc.SensorValue"
  ], 
  "status": "OK"
}

**Comment by nkskjames** [comment]
fixed in commit: 981f4dc59f23668b567949527c8e9585c2ab7089.

there was an inheritance bug with the virtual sensors.
