### ISSUE TITLE
Centaur0 has no properties

### ISSUE THREAD

**Issue by causten** [openbmc/skeleton#15]
There are no properties available against the Centaur.  I know the command works because in the example below I can see the cpu0 properties.  I also know properties should be there since the https://github.com/openbmc/skeleton/blob/master/bin/Palmetto.py#L194 shows some properties

$ curl http://9.3.164.147//org/openbmc/inventory/system/chassis/motherboard/centaur0
{
  "status": "OK"
}

$ curl http://9.3.164.147//org/openbmc/inventory/system/chassis/motherboard/cpu0
{
  "fault": "", 
  "fru_type": "CPU", 
  "is_fru": 1, 
  "present": "True"
}causten@causten-VirtualBox:~/gitstuff/phosphor-host-ipmid

**Comment by nkskjames** [comment]
I see properties on your system:
njames@bakerstreet:~/openbmc/skeleton$ curl http://9.3.164.147//org/openbmc/inventory/systm/chassis/motherboard/centaur0
{
  "fault": "None", 
  "fru_type": "MEMORY_BUFFER", 
  "is_fru": 0, 
  "present": "Inactive"

**Comment by nkskjames** [comment]
this is fixed:
/org/openbmc/inventory/system/chassis/motherboard/membuf0
Custom Field 1 = ECID:019A007001040718130D0000001C02D1
