### ISSUE TITLE
Can not power on

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#17]
I updated the latest commit af915f1251b4989f41829f9ae8589b42ef81efd7 and build. Then the system can not power on, both power button and obmcutil are not work. The state keep in BMC_STARTING.
I suppose the issue is caused by the commit create dependency between fan and chassis control  or add bmc flash capability .
![1448270643403](https://cloud.githubusercontent.com/assets/15260220/11333272/6ddf811a-9207-11e5-8f6f-6e108533755c.jpg)
![1448270645899](https://cloud.githubusercontent.com/assets/15260220/11333273/7092ba08-9207-11e5-9a44-c0a2cbe7a4a1.jpg)

**Comment by nkskjames** [comment]
this is fixed
