### ISSUE TITLE
Remove all `/dev/mem` access

### ISSUE THREAD

**Issue by shenki** [openbmc/skeleton#20]
Currently we poke at `/dev/mem` for making sure a bunch of things are configured in the way they need to be. This is bad, as userspace and the kernel can step on each others toes, and create bugs that are hard to debug.

Ultimately there will be proper kernel features in the form of device tree descriptions and a pinmux driver. For now, lets stick them in `arch/arm/mach-aspeed/aspeed.c`.

We could disable `/dev/mem` entirely, but it is useful for debugging and testing, so instead we will make it a rule that no checked in code touches it and keep it around for convenience.

**Comment by shenki** [comment]
@nkskjames will have a crack at this.

We can use the device tree to make this machine dependant. Something like https://github.com/shenki/linux/commit/98c91d9f2df27d8bb9c6e4633d9ffbc51b12852e

**Comment by nkskjames** [comment]
Fixed with https://github.com/openbmc/linux/commit/6da1b0f7943571e825ad06b3cdb990472cc07d2b
