### ISSUE TITLE
OCC online path is hardcoded

### ISSUE THREAD

**Issue by nkskjames** [openbmc/skeleton#33]
When the OCC becomes active, the sensor currently sets the online attribute to 1 for OCC hwmon driver.   It is using hardcoded path and is customized for Barreleye.  Need to remove hardcoding.

**Comment by nkskjames** [comment]
After revisiting, the main issue is that sensor_manager is system specific.  It instantiates sensors that are specific to a particular system.  Need to make generic.

**Comment by shenki** [comment]
Is this a kernel issue? Sounds more like userspace to me
