### ISSUE TITLE
Power cap setting is not working properly on Palmetto

### ISSUE THREAD

**Issue by mkumatag** [openbmc/skeleton#42]
Powercap settings are not really working properly on Palmetto box. Discussed with Yi LI - found to be code is written only for Barreleye and not dynamic enough to deal both platform.

**Comment by nkskjames** [comment]
Can you elaborate on this?   What is specific to Barreleye?

**Comment by mkumatag** [comment]
I discussed with Yi Li, he mentioned that in sensor_manager2.py, sysfs_attr is hardcoded to work for Barreleye platform, which should be different a path for palmetto platform.

```
## instantiate non-polling sensors
## these don't need to be in seperate process
## TODO: this should not be hardcoded

obj_path = OBJ_PATH+"/host/PowerCap"
sensor_obj = Sensors.PowerCap(bus,obj_path)
## hwmon3 is default for master OCC on Barreleye.
## should rewrite sensor_manager to remove hardcode
sensor_obj.sysfs_attr = "/sys/class/hwmon/hwmon3/user_powercap"
root_sensor.add(obj_path,sensor_obj)
```

**Comment by adamliyi** [comment]
Fixed here: https://github.com/openbmc/skeleton/pull/48
Tested on Palmetto.

**Comment by adamliyi** [comment]
Resubmitted a PR to fix this issue: https://github.com/openbmc/skeleton/pull/50
Each time setting PowerCap, skeleton will search for 'user_powercap" in '/sys/class/hwmon'. If not found, an exception will be returned. This will happen when OCC is not active, or for some reason, OCC is active, OCC device is not initialized.

**Comment by adamliyi** [comment]
If setting error, would expect an error code like bellow:

curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": [ 12000 ]}"  https://9.3.23.24/org/openbmc/sensors/host/PowerCap/action/setValue
{
  "data": {
    "description": "org.freedesktop.DBus.Python.TypeError: Cannot find user_powercap hwmon attribute, check occ status."
  }, 
  "message": "400 Bad Request", 
  "status": "error"
}

**Comment by adamliyi** [comment]
@mkumatag , I just set up the environment on a Palmetto: 9.3.164.149
Could you please verify this issue?
Thanks,
-Yi

**Comment by mkumatag** [comment]
Tested on that machine and working fine.
Test results:

## Get System Power Consumption :: Get the current system power consu... | PASS |

Test Occ Powercap :: This suite is for testing OCC: Power capping ... | PASS |
6 critical tests, 6 passed, 0 failed

# 6 tests total, 6 passed, 0 failed

Output:  /home/manjunath/git/openbmc-automation/output.xml
Log:     /home/manjunath/git/openbmc-automation/log.html
Report:  /home/manjunath/git/openbmc-automation/report.html
______________________________________________________________________________________________ summary ______________________________________________________________________________________________
  custom: commands succeeded
  congratulations :)
[manjunath@oc1275007250 openbmc-automation]$
