### ISSUE TITLE
Set powercap shouldn't except the values out of range

### ISSUE THREAD

**Issue by mkumatag** [openbmc/skeleton#43]
We have seen that set powercap call is excepting any values outside range like less than min or more than supported max powercap value. This error handling should be done in the REST API level to return with error instead of accepting as 200.

Note - though values are not written into the /org/openbmc/sensors/host/PowerCap which is expected but REST should also through Error message.

**Comment by adamliyi** [comment]
Please see PR:  https://github.com/openbmc/skeleton/pull/50
An exception will be returned when setting the power cap value out of range:

 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": [ 1900 ]}"  https://9.3.23.24/org/openbmc/sensors/hot/PowerCap/action/setValue
{
  "data": {
    "description": "Internal Server Error",
    "exception": "DBusException('Set PowerCap error: check value range',)",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 862, in _handle",
      "    return route.call(*_args)",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 1734, in wrapper",
      "    rv = callback(_a, **ka)",
      "  File \"/usr/sbin/obmc-rest\", line 569, in __call__",
      "    return self.callback(_a, *_kw)",
      "  File \"/usr/sbin/obmc-rest\", line 657, in wrap",
      "    resp = { 'data': callback(_a, *_kw) }",
      "  File \"/usr/sbin/obmc-rest\", line 622, in wrap",
      "    return callback(_a, *_kw)",
      "  File \"/usr/sbin/obmc-rest\", line 646, in wrap",
      "    return callback(_a, *_kw)",
      "  File \"/usr/sbin/obmc-rest\", line 79, in **call**",
      "    return getattr(self, 'do_' + request.method.lower())(*_kw)",
      "  File \"/usr/sbin/obmc-rest\", line 240, in do_post",
      "    return request.route_data['method'](*request.parameter_list)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/proxies.py\", line 145, in **call**",
      "    *_keywords)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking",
      "    message, timeout)",
      "DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Set PowerCap error: check value range"
    ]
  },
  "message": "500 Internal Server Error",
  "status": "error"
}

**Comment by mkumatag** [comment]
500 internal error is not really accepted, we should through 4xx series error. You can refer https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error to understand more about errors.

**Comment by adamliyi** [comment]
Thanks Manjunath  for reminding. I need to check with Brad.

**Comment by adamliyi** [comment]
Updated the PR.
Here is the new return code when setting invalid power cap value:

curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": [ 2000 ]}"  https://9.3.23.24/org/openbmc/sensors/host/PowerCap/action/setValue
{
  "data": {
    "description": "org.freedesktop.DBus.Error.InvalidArgs: Set PowerCap error: check value range"
  }, 
  "message": "400 Bad Request", 
  "status": "error"
}

**Comment by adamliyi** [comment]
@mkumatag , I've setup the barreley 9.3.23.24. Could you please verify issue #42, and issue #43.

I have replaced the two files on that server with my fix.
/usr/sbin/Sensors.py and /usr/sbin/sensor_manager2.py

Thanks,

**Comment by mkumatag** [comment]
I just verified the tests on that machine for issue #43 and working fine.

---

Test Occ Powercap :: This suite is for testing OCC: Power capping ... | PASS |
6 critical tests, 6 passed, 0 failed

# 6 tests total, 6 passed, 0 failed

Output:  /home/manjunath/git/openbmc-automation/output.xml
Log:     /home/manjunath/git/openbmc-automation/log.html
Report:  /home/manjunath/git/openbmc-automation/report.html
______________________________________________________________________________________________ summary ______________________________________________________________________________________________
  custom: commands succeeded
  congratulations :)
[manjunath@oc1275007250 openbmc-automation]$

**Comment by mkumatag** [comment]
Why this issue has been closed? is code already merged?
