### ISSUE TITLE
BMC does not transition to BMC_READY

### ISSUE THREAD

**Issue by anoo1** [openbmc/skeleton#54]
With the latest openbmc tag v06, upon boot, the BMC state remains at BMC_STARTING and never transitions to BMC_READY. The system can be powered on and all dbus processes seem to be running so may be just a missing state update.

**Comment by anoo1** [comment]
This only occurs on Palmetto.
Barreleye transitions to BMC_READY.

**Comment by bradbishop** [comment]
I have a fix for this here:  https://github.com/bradbishop/skeleton/tree/om but I haven't tried it on Barreleye yet....

**Comment by anoo1** [comment]
Fixed with https://github.com/openbmc/skeleton/pull/61 .
