### ISSUE TITLE
No event record while emergency shutdown

### ISSUE THREAD

**Issue by johnhcwang** [openbmc/skeleton#64]
There's no event to identify after emergency shutdown the system.
User have no idea when the system shutdown and why.

**Comment by anoo1** [comment]
@adamliyi will look at this

**Comment by adamliyi** [comment]
<img width="1014" alt="screen shot 2016-06-02 at 10 20 02 pm" src="https://cloud.githubusercontent.com/assets/14884975/15748174/58435a52-2910-11e6-9651-ba3f9a5fbf4d.png">
This feature looks not a feature of BMC. If Host OS or BIOS can send IPMI SEL command to BMC, with sensor type code "20h', BMC will log OS shutdown.

**Comment by johnhcwang** [comment]
BMC shutdown the system due to emergency state actively.
https://github.com/openbmc/skeleton/blob/master/bin/Sensors.py#L68
https://github.com/openbmc/skeleton/blob/master/bin/chassis_control.py#L209

**Comment by adamliyi** [comment]
Thanks @johnhcwang. So we will need a SEL when BMC shutdown the host due to warning or critical fails. According to "BMC Firmware Specification", "R3.2-1.16 In either case a SEL must be present" 

```
1.7.4 EPOW Power offs Phase 3
On occasion the BMC will be required to shut down the host due to high ambient
or fan fails. The types of faults are classified into warning and critical fails. For
Warning events the BMC should issue a graceful power off path, and allow the
host to quiesce activities. If the fail is Critical then the BMC should follow the
hard shutdown path.
The warning and critical events are part of the power/thermal management
algorithm.
BMC Requirements
R3.2-1.14 On warning EPOW events trigger graceful shutdown
R3.2-1.15 On Critical EPOW events trigger hard shutdown path
R3.2-1.16 In either case a SEL must be present
```

**Comment by adamliyi** [comment]
An patch (part of the fix) for phosphor-event has been submitted for review: 
https://gerrit.openbmc-project.xyz/#/c/13/
The other part of the fix will be submitted when skeleton is migrated to Gerrit.
