### ISSUE TITLE
DIMM reported 0xE500 when power on

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#71]
The memory seems occur memory ECC UE when power on.
[occputty2.txt](https://github.com/openbmc/skeleton/files/246430/occputty2.txt)
[Dimm16.log.txt](https://github.com/openbmc/skeleton/files/246429/Dimm16.log.txt)

**Comment by williamspatrick** [comment]
These cannot be caused by the BMC.  Are you certain you don't have a bad DIMM?
