### ISSUE TITLE
Sensor can not be read by dbus

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#73]
I add some sensors in Barreleye.py in '6-002e' and '6-002d'.
'fan1_input' : { 'object_path' : 'tach/fan2L','poll_interval' : 10000,'scale' : 1,'units' : '' }, 
'fan2_input' : { 'object_path' : 'tach/fan2H','poll_interval' : 10000,'scale' : 1,'units' : '' }, 
'fan3_input' : { 'object_path' : 'tach/fan1L','poll_interval' : 10000,'scale' : 1,'units' : '' }, 
'fan4_input' : { 'object_path' : 'tach/fan1H','poll_interval' : 10000,'scale' : 1,'units' : '' }, 
'fan5_input' : { 'object_path' : 'tach/fan0L','poll_interval' : 10000,'scale' : 1,'units' : '' }, 
'fan6_input' : { 'object_path' : 'tach/fan0H','poll_interval' : 10000,'scale' : 1,'units' : '' }, 
I can saw the values in /sys/class/hwmon/hwmon1 and  /sys/class/hwmon/hwmon2 are correct.
![imag5167](https://cloud.githubusercontent.com/assets/15260220/15074214/519b018c-13d0-11e6-8af0-0b028591b13f.jpg)
But the sensor reading is 0 by obmcutil getsensors.
![imag5168](https://cloud.githubusercontent.com/assets/15260220/15074221/557dbad8-13d0-11e6-9ec0-0b2b2c5ae5e6.jpg)

**Comment by anoo1** [comment]
Hi Ken, can you provide all the lines in your Barreleye.py that define fan*_input?
The lines posted only define fan 0-2 L/H, not the fan 4 H/L or 5 H/L on the screenshot.

I did see an interesting combination that if I define the same hwmon target twice:

```
                        'fan4_input' : { 'object_path' : 'tach/fan1H','poll_interval' : 10000,'scale' : 1,'units' : '' },
                        'fan4_input' : { 'object_path' : 'tach/fan4H','poll_interval' : 10000,'scale' : 1,'units' : '' },
```

then only the 2nd one (4H) is displayed and has the correct value, but 1H is not displayed:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
/org/openbmc/sensors/tach/fan4H
critical_lower = 0
critical_upper = 0
emergency_enabled = 0
error = 0
filename = /sys/class/hwmon/hwmon1/fan4_input
offset = 0
scale = 1
threshold_state = NORMAL
thresholds_enabled = 0
units = 
value = 22881
```

**Comment by Kenthliu** [comment]
Hi Adri
Below is my Barreleye.py
https://github.com/Kenthliu/skeleton/blob/master/bin/Barreleye.py
Any other place defined the hwmon?

**Comment by anoo1** [comment]
Thanks Ken. What driver level does the system have, and do you still see the value missing? I'm using your Barreleye.py and unable to recreate with v0.7 and v0.6.1. All the 12 values for the fan*input show up with "obmcutil getsensors".
Also is this value missing on other systems, and do you see the value set in hwmon1/2 when you run the getsensors command? I know you mentioned it's shown but just double checking :)

**Comment by Kenthliu** [comment]
I just check drver level /sys/class/hwmon/hwmon1 and /sys/class/hwmon/hwmon2, and did not see a ny miss the value. Yes, this issue is random. Not all of the systems can reproduce the symptom. The BMC is based on v0.6.1. So far I saw the symptom when relibility team do the heat up or cool down test. RAX also saw similar issue about fan LED, but I'm not sure if it's the same root cause.

**Comment by nkskjames** [comment]
can we get a journal log after you sample a 0 for the fan4_input?

**Comment by Kenthliu** [comment]
Still trying to reproduce. I found one system has the symptom, but did not add the debug code in hwmon.py.
Below are  /sys/class/hwmon and obmcutil getsensors
we can see /sys/class/hwmon/hwmon1/fan6_input has no value.
[FanTach.txt](https://github.com/openbmc/skeleton/files/258961/FanTach.txt)
Below is  journal log.
[Fanjournal.txt](https://github.com/openbmc/skeleton/files/258962/Fanjournal.txt)

**Comment by Kenthliu** [comment]
I did couple of experiment.
The system /sys/class/hwmon/hwmon1/fan5_input has no value. 
Add debug code in hwmon.py. Then I kill a hwmon and restart using "hwmon.py Barreleye". 
The sensor value back to normal.
[fanfail.txt](https://github.com/openbmc/skeleton/files/260597/fanfail.txt)
[fanjournal.txt](https://github.com/openbmc/skeleton/files/260598/fanjournal.txt)
Another system without kill current hwmon, and execute another hwmon. It's also back to normal.'
[fanfail2.txt](https://github.com/openbmc/skeleton/files/260599/fanfail2.txt)

**Comment by Kenthliu** [comment]
Here is the latest log. I modified Hwmon.py and run the test at the beginning.
We can see /sys/class/hwmon/hwmon1/fan3_input has no value. And the /hwmon1/fan3_input is miss in hwmon.py.

[fanled2.txt](https://github.com/openbmc/skeleton/files/261105/fanled2.txt)

**Comment by Kenthliu** [comment]
Please take a look Fanjournal.txt in https://github.com/openbmc/skeleton/issues/73#issuecomment-218407727

hwmon1/fan6_input add in
Apr 15 09:26:59 barreleye system_manager.py[936]: HWMON add: /org/openbmc/sensors/tach/fan3H : /sys/class/hwmon/hwmon1/fan6_input

But did not register sensor and create object like other sensors. 
Apr 15 09:27:25 barreleye system_manager.py[936]: HWMON: Attibute no longer exists: /sys/class/hwmon/hwmon1/fan6_input
The Hwmon init timing has something wrong.

**Comment by agangidi53** [comment]
Hi @Kenthliu 

I saw a red light on one of our barreleye's.  And went to check the "value" field from "obmcutil getsensors" related to fan 2. And realized that value is 0. 

Do you think we are running to the same issue ?

_>> obmcutil getsensors | grep fan2L -A 6_
/org/openbmc/sensors/tach/fan2L
critical_lower = 0
critical_upper = 0
emergency_enabled = 0
error = 0
filename = /sys/class/hwmon/hwmon2/fan1_input
offset = 0
scale = 1
threshold_state = NORMAL
thresholds_enabled = 0
units =
value = 0

**Comment by Kenthliu** [comment]
Hi Adi, looks like you saw the same issue on your site. When this issue happened, the driver's value in /sys/class/hwmon still fine. The hwmon.py's scanDirectory should load the attribute into dbus again. If it's convenience, please help to replace below code in `/usr/sbin/hwmon.py` in BMC console, and reboot BMC in the failure fan led system. That is add 2 print for dpath and attribute.
    def scanDirectory(self):
        devices = os.listdir(HWMON_PATH)
        found_hwmon = {}
        regx = re.compile('([a-z]+)\d+_')
        for d in devices:
            dpath = HWMON_PATH+'/'+d+'/'
            print dpath  
            found_hwmon[dpath] = True
            if (self.hwmon_root.has_key(dpath) == False):
                self.hwmon_root[dpath] = []
            ## the instance name is a soft link
            instance_name = os.path.realpath(dpath+'device').split('/').pop()

```
        if (System.HWMON_CONFIG.has_key(instance_name)):
            hwmon = System.HWMON_CONFIG[instance_name]

            if (hwmon.has_key('labels')):
                label_files = glob.glob(dpath+'/*_label')
                for f in label_files:
                    label_key = self.readAttribute(f)
                    if (hwmon['labels'].has_key(label_key)):
                        namef = f.replace('_label','_input')
                        self.addObject(dpath,namef,hwmon['labels'][label_key])
                    else:
                        pass
                        #print "WARNING - hwmon: label ("+label_key+") not found in lookup: "+f

            if hwmon.has_key('names'):
                for attribute in hwmon['names'].keys():
                    print attribute
                    self.addObject(dpath,dpath+attribute,hwmon['names'][attribute])

        else:
            print "WARNING - hwmon: Unhandled hwmon: "+dpath
```

**Comment by Kenthliu** [comment]
[fanledfail0518.txt](https://github.com/openbmc/skeleton/files/270410/fanledfail0518.txt)
When the issue happen scanDirectory can still work. By the log, hwmon2/fan4_input has no value, but we can still see the attribute in scanDirectory. After that I did another experiment, add some print in poll(self,objpath,attribute): as below.
    def poll(self,objpath,attribute):
        print attribute
        try:
            raw_value = int(self.readAttribute(attribute))
            print "1"
            obj = bus.get_object(SENSOR_BUS,objpath,introspect=False)
            print "2"
            intf = dbus.Interface(obj,HwmonSensor.IFACE_NAME)
            print "3"
            rtn = intf.setByPoll(raw_value)
            print "4"
            if (rtn[0] == True):
                self.writeAttribute(attribute,rtn[1])
                print "5"
After reproduce, the print attribute can not see when the symptom happen.
So I suspect the problem is in addObject(self,dpath,hwmon_path,hwmon):.
I also found that not only fan*_input senor, other sensor has no value randomly according to other log.

**Comment by adamliyi** [comment]
Ken and I are working on this issue. Ken has found the root cause:
In hwmon.py: open() in readAttribute() will trigger exception in certain cases (e.g, when Host CPU Power off, open() OCC hwmon attributes will trigger exception. OCC hwmon attributes will be deleted by scanDirectory() at some time (scanDirectory is called every 30s), but these attributes will exist for a while when Host CPU is power off).

The exception is not handled correctly. It will cause the caller function of readAttribute() - poll() and scanDirectory() terminate unexpected.

```
        def readAttribute(self,filename):
                val = ""
                with open(filename, 'r') as f:
                        for line in f:
                                val = line.rstrip('\n')
                return val
```

We add code to catch exception in readAttribute(), and Ken is testing it.

**Comment by Kenthliu** [comment]
@nkskjames The change in hwmon.py work. I will make a pull request for the fix recently. About sensor disappear sometime, it's another issue. Please help take a look into NCT7904 driver. Thanks.
