### ISSUE TITLE
BMC hang in BMC_STARTING, and does not transition to BMC_READY

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#75]
We found a similar issue as https://github.com/openbmc/skeleton/issues/54.
Now we have a system that can reproduce the symptom every time.
The system just did DC cycle and AC cycle test before the issue happen.
Attach the journalctl log.
[Hang_BMC_STARTING.txt](https://github.com/openbmc/skeleton/files/257025/Hang_BMC_STARTING.txt)

**Comment by nkskjames** [comment]
Looks like you added a debug statement that is causing an issue:

Apr 15 09:26:13 barreleye system_manager.py[922]: File "/usr/sbin/hwmon.py", line 53
Apr 15 09:26:13 barreleye system_manager.py[922]: print filename
Apr 15 09:26:14 barreleye system_manager.py[922]: ^
Apr 15 09:26:14 barreleye system_manager.py[922]: IndentationError: unexpected indent

This would prevent the fan sensors from being created which will stop it from getting to BMC_READY state

**Comment by Kenthliu** [comment]
Yes, you are right.
Thank you very much!
