### ISSUE TITLE
Setting 'preserve_network_settings' flag does not back up u-boot-env

### ISSUE THREAD

**Issue by agangidi53** [openbmc/skeleton#76]
Setting the "preserve_network_settings" flag and flashing the BMC, does not back up the u-boot environment variables.

Here are the steps I followed:

a) curl -c cjar -k -X POST -H "Content-Type: application/json" \  -d '{"data": [ "root", "0penBmc" ] }' \ https://1xx.xx.xx.xx/login

b) curl  -c cjar -b cjar -k https://xx.xx.xx.xx/org/openbmc/control/flash/bmc

c) curl -c cjar -b cjar -k -H "Content-Type: application/json" -X PUT -d "{\"data\": 1}" https://xx.xx.xx.xx/org/openbmc/control/flash/bmc/attr/preserve_network_settings

d) curl  -c cjar -b cjar -k https://xx.xx.xx.xx/org/openbmc/control/flash/bmc
{
  "data": {
    "clear_persistent_files": 0,
    "filename": "",
    "preserve_network_settings": 1,
    "restore_application_defaults": 0,
    "status": "Idle",
    "update_kernel_and_apps": 0
  },

e) curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": ["\"tt.tt.tt.tt\",\"final.tar\""]}" https://xx.xx.xx.xx/org/openbmc/control/flash/bmc/action/updateViaTftp

{
  "data": {
    "clear_persistent_files": 0,
    "filename": "final.tar",
    "preserve_network_settings": 1,
    "restore_application_defaults": 0,
    "status": "Update Success.  Please reboot.",
    "update_kernel_and_apps": 0
  },

f) Reboot

**Comment by agangidi53** [comment]
This issue was due to small bug in the code. The back uboot env image was being copied to the wrong location. 
This Fixes it:  https://github.com/openbmc/skeleton/pull/79

**Comment by causten** [comment]
Agangidi53, will you close this once you verify pull 79 fixes the issue.  Should be in Tag 0.8 and newer

**Comment by agangidi53** [comment]
sure Chris !!
