### ISSUE TITLE
Not setting 'clear_persistent_files' flag does not back up Static IP (Stored in persistent file system ?)

### ISSUE THREAD

**Issue by agangidi53** [openbmc/skeleton#77]
Here are the steps I follow and after rebooting at the end, static IP address (SUPPOSED TO BE STORED IN PERSISTENT PARTITION) gets cleared instead of being saved:

Here are the steps I followed:

a) Setting Static IP Address:

   ipmitool lan set 1 ipsrc static
   ipmitool lan set 1 ipaddr 10.127.xx.xx
   ipmitool lan set 1 netmask 255.255.252.0
   ipmitool lan set 1 defgw ipaddr 10.127.xx.xx

b) curl -c cjar -k -X POST -H "Content-Type: application/json" \ -d '{"data": [ "root", "0penBmc" ] }' \ https://1xx.xx.xx.xx/login

c) curl -c cjar -b cjar -k https://xx.xx.xx.xx/org/openbmc/control/flash/bmc

d) As you can see by default **clear_persistent_files** is set to 0 . Which means that persistent files should be backed up by default:

 curl -c cjar -b cjar -k https://xx.xx.xx.xx/org/openbmc/control/flash/bmc
{
"data": {
"clear_persistent_files": 0,
"filename": "",
"preserve_network_settings": 1,
"restore_application_defaults": 0,
"status": "Idle",
"update_kernel_and_apps": 0
},

e) curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": ["\"tt.tt.tt.tt\",\"final.tar\""]}" https://xx.xx.xx.xx/org/openbmc/control/flash/bmc/action/updateViaTftp

{
"data": {
"clear_persistent_files": 0,
"filename": "final.tar",
"preserve_network_settings": 1,
"restore_application_defaults": 0,
"status": "Update Success. Please reboot.",
"update_kernel_and_apps": 0
},

f) Reboot

**Comment by agangidi53** [comment]
This is fixed with https://github.com/openbmc/skeleton/pull/79
I will close this issue after I verify the new master

**Comment by causten** [comment]
Tag 0.8 and newer contain this fix
