### ISSUE TITLE
PreTag  openbmc/skeleton#43  - Set Less Than Minimum PowerCAP

### ISSUE THREAD

**Issue by gkeishin** [openbmc/skeleton#97]
Please refer to https://github.com/mkumatag/openbmc-automation/issues/61
for detail description...

Our concern was if this is some sort of REST server code bug returning Error even when that PowerCap property existing on the system..

If by design ( openbmc/skeleton#43 ) if itis not going to return HTTP OK ... then, why is this return HTTP OK here on Palmetto and throwing error on Barrelleye when PowerCap Property exist on both the systems..

Example:

On Palmetto :
openbmc-automation$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": [ 1900 ]}" http://9.3.164.177/org/openbmc/sensors/host/PowerCap/action/setValue
{
"data": null,
"message": "200 OK",
"status": "ok"
}

On Barrelleye:
openbmc-automation$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST-d "{\"data\": [ 1900 ]}" https://9.3.23.24/org/openbmc/sensors/host/PowerCap/action/setValue
{
"data": {
"description": "org.openbmc.objectmapper.Error.NotFound: path or object not found: /org/openbmc/sensors/host/PowerCap"
},
"message": "404 Not Found",
"status": "error"
}

**Comment by gkeishin** [comment]
We are seeing the powercap setting errors now frequently.
Tests . Test Generic Conf
7 Test  4 pass   3  3 failed

out of 7 , 3 are failing

/org/openbmc/settings/host0, power_cap
1. Set the power with string of characters (abcdefg)
2. Set the power with greater then MAX_POWER_VALUE (1010)

/org/openbmc/settings/host0, boot_flags
1. Set the boot flags with string ( 3ab56f )

We would like to know what are the valid policies and what are not from those attributes..

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc #557](https://github.com/openbmc/openbmc/issues/557) via [**ZenHub**](https://www.zenhub.com/)
